# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='community',
        ),
    ]
